src/Entity/Command.php
<?php

namespace App\Entity;

use App\Repository\CommandRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommandRepository::class)
 */
class Command
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $number_order;

    /**
     * @ORM\Column(type="text")
     */
    private $adress;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\ManyToMany(targetEntity=Product::class, inversedBy="commands")
     */
    private $products;

    public function __construct()
    {
        $this->products = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getNumberOrder(): ?string
    {
        return $this->number_order;
    }

    public function setNumberOrder(string $number_order): self
    {
        $this->number_order = $number_order;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * @return Collection|Product[]
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Product $product): self
    {
        if (!$this->products->contains($product)) {
            $this->products[] = $product;
        }

        return $this;
    }

    public function removeProduct(Product $product): self
    {
        $this->products->removeElement($product);

        return $this;
    }
}

src/Controller/Front/BrandController.php
<?php

namespace App\Controller\Front;

use App\Entity\Product;
use App\Repository\BrandRepository;
use App\Repository\MediaRepository;
use App\Repository\ProductRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;



class BrandController extends AbstractController
{


      
    /**
     * @Route("front/brands/", name="front_list_brand")
     */
    public function listBrands(BrandRepository $brandRepository)
    {
        $brands = $brandRepository->findAll(); 
        return $this->render('front/brands.html.twig', ['brands' => $brands]);
    }


    /**
     * @Route("front/brand/{id}", name="front_show_brand")
     */
    public function showBrand($id, brandRepository $brandRepository)
    {
        $brand = $brandRepository->find($id); 
        
        return $this->render('front/brand.html.twig', ['brand' => $brand]);
    }

}

src/Controller/Front/CommandController.php
<?php

namespace App\Controller\Front;



use App\Repository\CommandRepository;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;




class CommandController extends AbstractController
{


      
 
    public function listCommands(CommandRepository $commandRepository)
    {
        $commands = $commandRepository->findAll(); 
        return $this->render('front/commands.html.twig', ['commands' => $commands]);
    }


   
    public function showCommand($id, CommandRepository $commandRepository)
    {
        $command = $commandRepository->find($id); 
        
        return $this->render('front/command.html.twig', ['command' => $command]);
    }

}

src/Controller/Front/ProductController.php
<?php

namespace App\Controller\Front;

use App\Entity\Like;
use App\Entity\Product;
use App\Repository\LikeRepository;
use App\Repository\MediaRepository;
use App\Repository\ProductRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;






class ProductController extends AbstractController
{

    // creer les 2 fct qui affichent la liste des produits avec leur name
    // prix et le name de leur type et le name d eleur brand

    //affiche grace a lid un produit en particulier et toutes les info


  



    /**
     * @Route("front/products/", name="front_list_product")
     */
    public function listProduct(ProductRepository $productRepository)
    {
        $products = $productRepository->findAll(); 
        return $this->render('front/products.html.twig', ['products' => $products]);
    }


    /**
     * @Route("front/product/{id}", name="front_show_product")
     */
    public function showProduct($id, ProductRepository $productRepository)
    {
        $product = $productRepository->find($id); 
        
        return $this->render('front/product.html.twig', ['product' => $product]);
    }


    /**
     * @Route("front/search/", name="front_search")
     */
    public function frontSearch(ProductRepository $productRepository, Request $request)
    {
        //recuperer els donnes du tableau
        $term = $request->query->get('term');// query car le form est en get. si form en post alors use request au lieu de query

        $products = $productRepository->searchByTerm($term);
        
        
        return $this->render('front/search.html.twig', ['products' => $products]);
    }


    /**
     * @Route("front/like/product/{id}", name="product_like")
     */
    public function likeProduct($id, ProductRepository $productRepository, EntityManagerInterface $entityManagerInterface, LikeRepository $likeRepository)
    {
        $product = $productRepository->find($id);
        $user = $this->getUser();

        if(!$user)
        {
            return $this->json([
                'code' => 403,
                'message' => "Vous devez être connecté"
            ], 403);
        }

        if($product->isLikedByUser($user))
        {
            $like = $likeRepository->findOneBy([
                'product' => $product,
                'user' => $user
            ]);
            $entityManagerInterface->remove($like);
            $entityManagerInterface->flush();

            return$this->json([
                'code' => 200,
                'message' => "Le like a été supprimé",
                'likes' => $likeRepository->count(['product' => $product])
            ], 200);
        }

        $like = new Like();
        $like->setProduct($product);
        $like->setUser($user);

        $entityManagerInterface->persist($like);
        $entityManagerInterface->flush();

        return$this->json([
            'code' => 200,
            'message' => "Le like a été enregistré",
            'likes' => $likeRepository->count(['product' => $product])
        ], 200);

    }

}

src/Controller/Front/TypeController.php
<?php

namespace App\Controller\Front;

use App\Entity\Product;
use App\Repository\MediaRepository;
use App\Repository\ProductRepository;
use App\Repository\TypeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


class TypeController extends AbstractController
{
    
    /**
     * @Route("front/types/", name="front_list_type")
     */
    public function listTypes(TypeRepository $typeRepository)
    {
        $types = $typeRepository->findAll(); 
        return $this->render('front/types.html.twig', ['types' => $types]);
    }


    /**
     * @Route("front/type/{id}", name="front_show_type")
     */
    public function showType($id, TypeRepository $typeRepository)
    {
        $type = $typeRepository->find($id); 
        
        return $this->render('front/type.html.twig', ['type' => $type]);
    }




}

src/Controller/Front/UserController.php
<?php

namespace App\Controller\Front;

use App\Entity\User;
use App\Form\UserType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;

class UserController extends AbstractController
{

     /**
     * @Route("front/user/insert", name="insert_user")
     */
      public function insertUser(Request $request, EntityManagerInterface $entityManagerInterface, UserPasswordHasherInterface $userPasswordHasherInterface)
      {
        $user = new User();
        $userForm = $this->createForm(UserType::class, $user);

        $userForm->handleRequest($request);

        if($userForm->isSubmitted() && $userForm->isValid()){
            $user->setRoles(['ROLE_USER']);

            // on recup le password entre ds le form
            $plainPassword = $userForm->get('password')->getData();
            // on hash le password pour le securisé
            $hashedPassword = $userPasswordHasherInterface->hashPassword($user, $plainPassword);
            $user->setPassword($hashedPassword);

            $entityManagerInterface->persist($user);
            $entityManagerInterface->flush();

            return $this->redirectToRoute("front_list_product");

        }

        return $this->render('front/userform.html.twig', ['userForm' => $userForm->createView()]);

      }
        
}

templates/front/base.html.twig
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <title>Document</title>
</head>
<body>
    <header>
        <form action="{{ path('front_search') }}" method="get">
            <input type="search" name="term" id="">
            <input type="submit" value="Rechercher">        
        </form>

    </header>

    {% block main %}{% endblock %}
    
</body>
</html>

templates/front/brand.html.twig
{% extends "front/base.html.twig" %}


{% block main %}
    

    <h2>        {{ brand.name }}          </h2>
    <p>         {{ brand.description }}   </p>  
    
    <h3>Liste des articles de la marque :</h3>
    {% for produit in brand.products %}

        <h3>  {{ produit.name }} </h3>  
        
    {% endfor %}
   

    

   
  
   
{% endblock %}

templates/front/brands.html.twig
{% extends "front/base.html.twig" %}


{% block main %}
    {{batman}}

    <h1>Liste des marques</h1>

    <div class="brand-content">  

        {% for brand in brands %}
        <div class="brand-card">
            
            <a href="{{ path('front_show_brand', { 'id' : brand.id }) }}" >
                <h2  > {{ brand.name }} </h2>
            </a>
          
            
          
        </div>          
        {% endfor %}


    </div>


    <hr>

    

    {% for gproduct in gproducts.getAll %}

        <h3>{{ gproduct.name }}</h3>
        
    {% endfor %}

    <hr>

    {% for gtype in gtypes.getAll %}

        <h3>{{ gtype.name }}</h3>
        
    {% endfor %}

      <hr>

    {% for gbrand in gbrands.getAll %}

        <h3>{{ gbrand.name }}</h3>
        
    {% endfor %}


    
{% endblock %}

templates/front/command.html.twig
{% extends "front/base.html.twig" %}


{% block main %}
    

    <h2>        {{ command.numberOrder }}          </h2>
      
    
    <h3>Liste des articles de la commande :</h3>
    {% for produit in command.products %}

        <h3>  {{ produit.name }} </h3>  
        
    {% endfor %}
   

    

   
  
   
{% endblock %}

templates/front/commands.html.twig
{% extends "front/base.html.twig" %}


{% block main %}
    

    <h1>Liste des commandes</h1>

    <div class="command-content">  

        {% for command in commands %}
        <div class="command-card">
            
            <a href="{{ path('front_show_command', { 'id' : command.id }) }}" >
                <h2  > {{ command.numberOrder }} </h2>
            </a>
          
            
          
        </div>          
        {% endfor %}


    </div>


    <hr>

    



    
{% endblock %}

templates/front/product.html.twig
{% extends "front/base.html.twig" %}


{% block main %}
    

    <h2>        {{ product.name }}          </h2>

    <h3>        {{ product.price }}         </h3>
    <h3>        {{ product.stock }}         </h3>
    <p>         {{ product.description }}   </p>  
    
    <h3>        {{ product.type.name }}     </h3>
    <h3>        {{ product.brand.name }}    </h3>

    {% for image in product.media %}

    <img src="{{ asset('media/' ~ image.src ) }}" alt="{{ image.alt }}">
        
    {% endfor %}

    

   
  
   
{% endblock %}

 

    
   

templates/front/products.html.twig
{% extends "front/base.html.twig" %}


{% block main %}

    <h1>Liste des produits</h1>

    <div class="product-content">  

        {% for product in products %}
        <div class="product-card">
            
            <a href="{{ path('front_show_product', { 'id' : product.id }) }}" >
                <h2  > {{ product.name }} </h2>
            </a>
            <h3> Prix :  {{ product.price }} euros. </h3>
            <h3> type :  {{ product.type.name }}. </h3>
            <h3> Marque : {{ product.brand.name }}. </h3>

            <a href="{{ path("product_like", {'id' : product.id})  }}" class="btn btn-link js-likes">

{# app;user est la variable qui enregistre le user connecté si personne nest connecte la variable est vide #}
            {% if app.user and product.isLikedByUser(app.user) %}
                    <i class="fas fa-thumbs-up"></i>
                {% else %}
                    <i class="far fa-thumbs-up"></i>            
            {% endif %}
			    <span class="js-likes">{{ product.likes | length}}</span>
			    <span class="js-label">J'aime</span>
		    </a>
          
        </div>          
        {% endfor %}

    </div>
    


<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script>
		function onClickLike(event) {
    event.preventDefault();
    const url = this.href;
    const spanCount = this.querySelector('span.js-likes');
    const icone = this.querySelector('i');
    axios.get(url).then(function (response) {
    spanCount.textContent = response.data.likes;
    if (icone.classList.contains('fas')) {
    icone.classList.replace('fas', 'far');
    } else {
    icone.classList.replace('far', 'fas');
    }
    }).catch(function (error) {
        if (error.response.status === 403) {
            window.alert("Connexion requise");
        } else {
            window.alert("Une erreur s'est produite");
        }
        })
    }
    document.querySelectorAll('a.js-likes').forEach(function (link) {
    link.addEventListener('click', onClickLike);
    })
</script>
  
{% endblock %}

templates/front/search.html.twig
{% extends "front/base.html.twig" %}

{% block main %}

    <h1>les poduits qui correspondent à votre recherche sont : </h1>

    {% for product in products %}
        <h3> {{product.name}} </h3>
        
    {% endfor %}


{% endblock %}

templates/front/type.html.twig
{% extends "front/base.html.twig" %}


{% block main %}
    

    <h2>        {{ type.name }}          </h2>
    <h3>         {{ type.description }}   </h3>  
    
    <h3>Liste des articles du type :</h3>
    {% for produit in type.products %}

        <a href="{{ path('front_show_product', { 'id' : produit.id }) }}" >
            <h4>  {{ produit.name }} </h4>  
        </a>
    {% endfor %}
   

    

   
  
   
{% endblock %}

templates/front/types.html.twig
{% extends "front/base.html.twig" %}


{% block main %}

    <h1>Liste des types</h1>

    <div class="type-content">  

        {% for type in types %}
        <div class="type-card">
            
            <a href="{{ path('front_show_type', { 'id' : type.id }) }}" >
                <h2  > {{ type.name }} </h2>
            </a>
          
            
          
        </div>          
        {% endfor %}

    </div>
    
{% endblock %}

templates/front/userform.html.twig
{% extends "front/base.html.twig" %}


{% block main %}
    



	{{form(userForm)}}


   
{% endblock %}